- hosts: localhost
  connection: local

  vars:
      version: "0.12.2"
  tasks:
    - name: toolkit {{ version }}
      debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
